# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.2'
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: 'ui/package-lock.json'
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: Run Bandit security linter.
        args: [ "-ll" ]
        files: .py$
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
  - repo: local
    hooks:
      - id: pytest  # There is no pytest hook as yet.
        name: Run unit tests.
        # To validate coverage, change --cov-fail-under to the minimum.
        entry: bash -c 'pytest --cov=ecrf --cov-report=term --cov-fail-under=0 tests/'
        language: system
        pass_filenames: false
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        args: [ "feat", "fix", "ci", "chore", "test", "wip" ]
  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.7"
    hooks:
      - id: vulture
        name: Run vulture to look for dead code.
